server:
  port: 8086


info:
  app:
    name: Student Register API
    version: 1.0
    description: API de registro de alumnos



spring:
  application:
    name: api-student-register

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
