server:
  servlet:
    encoding: 
      charset: UTF-8
      enabled: true

spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9010/realms/student-realm
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  r2dbc:
    url: r2dbc:h2:file:///C:/h2/studentdb
    username: sa
    password:

  devtools:
    livereload:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: always
  info:
    env:
      enabled: true
logging:
  level:
    org.springframework.web.reactive: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth2.server.resource: TRACE
    org.springframework.web: TRACE
    org.springframework.http: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG
    io.r2dbc.spi: DEBUG
    io.r2dbc.h2: TRACE
    org.springframework.r2dbc: TRACE
