server:
  servlet:
    encoding: 
      charset: UTF-8
      enabled: true

spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/student-realm
      
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: always
  info:
    env:
      enabled: true
logging:
  level:
    org.springframework.web.reactive: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth2.server.resource: TRACE
    org.springframework.web: TRACE
    org.springframework.http: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG
    io.r2dbc.h2: DEBUG
    org.springframework.r2dbc: DEBUG
